apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-management
  name: server
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-management
  template:
    metadata:
      labels:
        app: product-management
    spec:
      containers:
        - image: mirshahriar/marketplace:latest
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 8080
              protocol: TCP
          args:
            - "serve"
