apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: marketplace
spec:
  template:
    spec:
      containers:
        - name: migration
          image: mirshahriar/marketplace:latest
          imagePullPolicy: Always
          args:
            - "migrate"
      restartPolicy: Never
