apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: github.com/mirshahriar/marketplace
spec:
  template:
    spec:
      containers:
        - name: migration
          image: mirshahriar/github.com/mirshahriar/marketplace:latest
          imagePullPolicy: Always
          args:
            - "migrate"
      restartPolicy: Never
