apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-management
  name: product-management
  namespace: github.com/mirshahriar/marketplace
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: product-management
  type: ClusterIP

